"""HuggingFace-native personal-model path (all optional, lazy imports).

The 2026 stack (AutoTrain is dead — HF says use TRL/Axolotl/Trainer):
1. push_files() — upload sft/dpo/card to YOUR dataset repo (private by
   default) via huggingface_hub. This is "the bot creating on the account".
2. training_script() — one-file TRL SFT+LoRA then DPO script. Runs on any
   GPU box / Colab / HF GPU Space; pushes adapters + merged model back.
3. space_app() — Gradio scaffold to SERVE the personal model from your
   account with a chat UI (+ notes for a /v1 OpenAI-compat endpoint the
   bot can consume via its existing openai provider kind).

Nothing here imports huggingface_hub at module load; every function degrades
to clear instructions when the package/token is missing. Tests inject a fake
api client — no network ever.
"""
from __future__ import annotations

import os


def push_files(repo_id: str, files: dict, token: str = "",
               repo_type: str = "dataset", private: bool = True,
               _api=None) -> dict:
    """Upload local files to a Hub repo. files: {local_path: repo_path}."""
    token = token or os.environ.get("HF_TOKEN") or ""
    if not token and _api is None:
        return {"ok": False, "error": "need HF_TOKEN (env or login)"}
    if not repo_id or "/" not in repo_id:
        return {"ok": False, "error": "need repo like user/dataset-name"}
    try:
        api = _api
        if api is None:
            from huggingface_hub import HfApi
            api = HfApi(token=token)
        api.create_repo(repo_id, repo_type=repo_type, private=private,
                        exist_ok=True)
        pushed = []
        for local, remote in files.items():
            api.upload_file(path_or_fileobj=str(local), path_in_repo=remote,
                            repo_id=repo_id, repo_type=repo_type)
            pushed.append(remote)
        return {"ok": True, "repo": repo_id, "pushed": pushed}
    except ImportError:
        return {"ok": False,
                "error": "pip install huggingface_hub (then retry)"}
    except Exception as e:
        return {"ok": False, "error": str(e)[:300]}


def training_script(model: str = "Qwen/Qwen2.5-1.5B-Instruct",
                    dataset: str = "user/personal-sft",
                    out: str = "user/personal-devon") -> str:
    """One-file TRL recipe: SFT + LoRA, then DPO prefs. Copy-paste runnable."""
    return f'''"""Personal-model training: SFT + LoRA, then DPO. Generated by the bot.
Run on any CUDA box / Colab / HF GPU Space:
  pip install -q trl peft transformers datasets accelerate bitsandbytes
  python train_personal.py   # needs HF_TOKEN with write access
"""
import os
from datasets import load_dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import DPOTrainer, DPOConfig, SFTTrainer, SFTConfig

BASE = "{model}"
DATA = "{dataset}"
OUT = "{out}"

tok = AutoTokenizer.from_pretrained(BASE)
if tok.pad_token is None:
    tok.pad_token = tok.eos_token
lora = LoraConfig(r=16, lora_alpha=32, lora_dropout=0.05,
                  task_type="CAUSAL_LM")

# ---- stage 1: SFT on your chats ----
sft_ds = load_dataset(DATA, data_files="sft.jsonl", split="train")
sft_cfg = SFTConfig(output_dir="out-sft", num_train_epochs=2,
                    per_device_train_batch_size=2,
                    gradient_accumulation_steps=8,
                    learning_rate=2e-4, logging_steps=10,
                    push_to_hub=True, hub_model_id=OUT + "-sft")
SFTTrainer(model=BASE, train_dataset=sft_ds, args=sft_cfg,
           peft_config=lora).train()

# ---- stage 2: DPO on your .good/.bad verdicts ----
try:
    dpo_ds = load_dataset(DATA, data_files="dpo.jsonl", split="train")
    dpo_cfg = DPOConfig(output_dir="out-dpo", num_train_epochs=1,
                        per_device_train_batch_size=2,
                        gradient_accumulation_steps=8,
                        learning_rate=5e-5, logging_steps=10,
                        push_to_hub=True, hub_model_id=OUT)
    DPOTrainer(model=OUT + "-sft", ref_model=None, args=dpo_cfg,
               train_dataset=dpo_ds, peft_config=lora).train()
    print("DPO done →", OUT)
except Exception as e:
    print("DPO skipped (need dpo.jsonl with chosen+rejected):", e)

print("next: quantize to GGUF (llama.cpp) for the phone, or serve on a Space.")
'''


def space_app(model_id: str = "user/personal-devon") -> dict:
    """Gradio Space scaffold that serves the personal model from the account."""
    app_py = f'''"""Personal-model Space. Deploy: new Space (Gradio SDK, GPU) + paste."""
import gradio as gr
from transformers import pipeline

MODEL = "{model_id}"
chat = pipeline("text-generation", model=MODEL, max_new_tokens=512,
                do_sample=True, temperature=0.7)

def reply(message, history):
    prompt = ""
    for u, a in history:
        prompt += f"USER: {{u}}\\nASSISTANT: {{a}}\\n"
    prompt += f"USER: {{message}}\\nASSISTANT:"
    out = chat(prompt)[0]["generated_text"][len(prompt):].strip()
    return out.split("USER:")[0].strip()

gr.ChatInterface(reply, title="personal devon").launch()
'''
    readme = f'''---
title: personal-devon
sdk: gradio
suggested_hardware: t4-small
---
# personal devon — served from this account
Base: {model_id}. For an OpenAI-compatible `/v1` endpoint the bot can
consume directly (GQ_PROVIDER=openai + GQ_BASE_URL), use a TGI/vLLM Space
or an HF Inference Endpoint instead of this Gradio UI.
'''
    return {"app.py": app_py, "README.md": readme}
